
settings:
  username: "fcalderon91"
  commit_msg: "⚡ Update README with recent activity"
  max_lines: 10
  readme_file: "./README.md"

  # Include relevant activity types
  whitelisted_events:
    - "push"
    - "pr"
    - "issues"
    - "comments"
    - "review"
    - "create_repo"
    - "fork"
    - "release"
    - "star"

  # Display dates in Spain
  date:
    timezone: "Europe/Madrid"
    text: "Last updated: {DATE}"
    format: "dd/mm/yyyy HH:MM:ss"

  commit_name: "github-actions[bot]"
  commit_email: "41898282+github-actions[bot]@users.noreply.github.com"

  line_prefix: "{NUM}. "

  ignored_repos: []

messages:
  push: "⬆️ Pushed {AMOUNT} commit(s) to {REPO}"
  pr_opened: "💪 Opened PR {ID} in {REPO}"
  pr_closed: "❌ Closed PR {ID} in {REPO}"
  pr_merged: "🎉 Merged PR {ID} in {REPO}"
  issue_opened: "❗ Opened issue {ID} in {REPO}"
  issue_closed: "✔️ Closed issue {ID} in {REPO}"
  comments: "💬 Commented on {ID} in {REPO}"
  new_star: "⭐ Starred {REPO}"
  fork_repo: "🔱 Forked {FORK} from {REPO}"
