
name: Update GitHub Activity

on:
  schedule:
    - cron: "17 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-activity:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update GitHub Activity
        uses: TheDanniCraft/activity-log@v1
        with:
          GITHUB_USERNAME: "fcalderon91"
          GITHUB_TOKEN: ${{ secrets.PROFILE_RECENT_ACTIVITY_TOKEN }}
          EVENT_LIMIT: 10
          README_PATH: README.md
          HIDE_DETAILS_ON_PRIVATE_REPOS: false
